/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServerRouteRouteImport } from './routes/server/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerDmRouteRouteImport } from './routes/server/dm/route'
import { Route as ServerDmIndexRouteImport } from './routes/server/dm/index'
import { Route as ServerDmFriendsRouteImport } from './routes/server/dm/friends'
import { Route as ServerDmUserUserIdRouteImport } from './routes/server/dm/user/$userId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRouteRoute = ServerRouteRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerDmRouteRoute = ServerDmRouteRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => ServerRouteRoute,
} as any)
const ServerDmIndexRoute = ServerDmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServerDmRouteRoute,
} as any)
const ServerDmFriendsRoute = ServerDmFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => ServerDmRouteRoute,
} as any)
const ServerDmUserUserIdRoute = ServerDmUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => ServerDmRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/server': typeof ServerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/server/dm': typeof ServerDmRouteRouteWithChildren
  '/server/dm/friends': typeof ServerDmFriendsRoute
  '/server/dm/': typeof ServerDmIndexRoute
  '/server/dm/user/$userId': typeof ServerDmUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/server': typeof ServerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/server/dm/friends': typeof ServerDmFriendsRoute
  '/server/dm': typeof ServerDmIndexRoute
  '/server/dm/user/$userId': typeof ServerDmUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/server': typeof ServerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/server/dm': typeof ServerDmRouteRouteWithChildren
  '/server/dm/friends': typeof ServerDmFriendsRoute
  '/server/dm/': typeof ServerDmIndexRoute
  '/server/dm/user/$userId': typeof ServerDmUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/server'
    | '/login'
    | '/register'
    | '/server/dm'
    | '/server/dm/friends'
    | '/server/dm/'
    | '/server/dm/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/server'
    | '/login'
    | '/register'
    | '/server/dm/friends'
    | '/server/dm'
    | '/server/dm/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/server'
    | '/login'
    | '/register'
    | '/server/dm'
    | '/server/dm/friends'
    | '/server/dm/'
    | '/server/dm/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServerRouteRoute: typeof ServerRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/dm': {
      id: '/server/dm'
      path: '/dm'
      fullPath: '/server/dm'
      preLoaderRoute: typeof ServerDmRouteRouteImport
      parentRoute: typeof ServerRouteRoute
    }
    '/server/dm/': {
      id: '/server/dm/'
      path: '/'
      fullPath: '/server/dm/'
      preLoaderRoute: typeof ServerDmIndexRouteImport
      parentRoute: typeof ServerDmRouteRoute
    }
    '/server/dm/friends': {
      id: '/server/dm/friends'
      path: '/friends'
      fullPath: '/server/dm/friends'
      preLoaderRoute: typeof ServerDmFriendsRouteImport
      parentRoute: typeof ServerDmRouteRoute
    }
    '/server/dm/user/$userId': {
      id: '/server/dm/user/$userId'
      path: '/user/$userId'
      fullPath: '/server/dm/user/$userId'
      preLoaderRoute: typeof ServerDmUserUserIdRouteImport
      parentRoute: typeof ServerDmRouteRoute
    }
  }
}

interface ServerDmRouteRouteChildren {
  ServerDmFriendsRoute: typeof ServerDmFriendsRoute
  ServerDmIndexRoute: typeof ServerDmIndexRoute
  ServerDmUserUserIdRoute: typeof ServerDmUserUserIdRoute
}

const ServerDmRouteRouteChildren: ServerDmRouteRouteChildren = {
  ServerDmFriendsRoute: ServerDmFriendsRoute,
  ServerDmIndexRoute: ServerDmIndexRoute,
  ServerDmUserUserIdRoute: ServerDmUserUserIdRoute,
}

const ServerDmRouteRouteWithChildren = ServerDmRouteRoute._addFileChildren(
  ServerDmRouteRouteChildren,
)

interface ServerRouteRouteChildren {
  ServerDmRouteRoute: typeof ServerDmRouteRouteWithChildren
}

const ServerRouteRouteChildren: ServerRouteRouteChildren = {
  ServerDmRouteRoute: ServerDmRouteRouteWithChildren,
}

const ServerRouteRouteWithChildren = ServerRouteRoute._addFileChildren(
  ServerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServerRouteRoute: ServerRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
